server:
  port: 8081

# LanXin 配置 - JitPack测试
langchain4j:
  vivo-lanxin:
    enabled: true
    app-id: your-app-id
    app-key: your-secret-key
    domain: api-ai.vivo.com.cn
    uri: /vivogpt/completions
    method: POST
    model-name: vivo-BlueLM-V-2.0
    stream-uri: /vivogpt/completions/stream

    # 模型参数配置
    model:
      temperature: 0.7
      max-output-tokens: 2048
      max-input-tokens: 8192

    # 模型信息配置
    info:
      provider: vivo
      display-name: vivo 蓝心大模型 (JitPack版本)
      version: "1.0"
      features:
        - chat
        - streaming
        - multi-turn

    # 线程池配置
    thread-pool:
      core-pool-size: 2
      maximum-pool-size: 10
      queue-capacity: 100
      keep-alive-time: 660

# 日志配置
logging:
  level:
    ink.lusy.lanxinmodel: DEBUG
    com.github.lusy37: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
